version: '3.6'

services:
  flxwebapi:
    image: fabreguesm/flexxus-bi-etl:latest
    ports:
      - '5050:8080'
    networks:
      - traefik               
    deploy:      
      placement:
        constraints: ["${NODE}"] 
    environment:
      - LOAD_MODE=FULL
      - INCREMENTAL_DAYS=5
      - LOG_LEVEL=INFO
      - MYSQL_HELPDESK_HOST=mngservicios.flexxus.com.ar
      - MYSQL_HELPDESK_PORT=15172
      - MYSQL_HELPDESK_USER=root
      - MYSQL_HELPDESK_PASSWORD=Flexxus2023**
      - MYSQL_HELPDESK_DATABASE=helpdesk
      - MARIADB_ISABELLE_HOST=192.168.121.5
      - MARIADB_ISABELLE_PORT=3306
      - MARIADB_ISABELLE_USER=areaprocesosflx
      - MARIADB_ISABELLE_PASSWORD=8j7%aUiMin76L3!xNF$T
      - MARIADB_ISABELLE_DATABASE=call_center
      - MARIADB_ASTERISK_HOST=192.168.121.5
      - MARIADB_ASTERISK_PORT=3306
      - MARIADB_ASTERISK_USER=areaprocesosflx
      - MARIADB_ASTERISK_PASSWORD=8j7%aUiMin76L3!xNF$T
      - MARIADB_ASTERISK_DATABASE=asteriskcdrdb
      - FIREBIRD_SAR_HOST=192.168.121.178
      - FIREBIRD_SAR_DATABASE=//SAR/Base/DBADMINISTRADOR.GDB
      - FIREBIRD_SAR_USER=Sysdba    
      - FIREBIRD_SAR_PASSWORD=3122414422
      - FIREBIRD_SAR_PORT=3050
      - FIREBIRD_FLX_HOST=192.168.121.18
      - FIREBIRD_FLX_DATABASE=Z:\Datacenter\Bases\Demo Servicios\DB-DEMO SERVICIOS.gdb
      - FIREBIRD_FLX_PORT=3050
      - FIREBIRD_FLX_USER=Sysdba
      - FIREBIRD_FLX_PASSWORD=3122414422
      - BIGQUERY_PROJECT_ID=flexxus-bi
      - BIGQUERY_DATASET_SOPORTE=soporte
      - BIGQUERY_DATASET_JIRA=jira
      - BIGQUERY_ENABLED=true
      - JIRA_BASE_URL=https://flexxus.atlassian.net/
      - JIRA_EMAIL=martinf@flexxus.com.ar
      - JIRA_API_TOKEN=ATATT3xFfGF0N9_8eoB4C7zAUJ9KD6tUqe_skY-X9uin830Iw1dcKfYq9L1RGH6FpGWR5aPt8h8EgUd9b_9tACKVdOthYS8ShinLE-6bdSlRyqIp7oA07HaFw8kz455qV23plK8oxmFpmCcUC_ynj_vbrvZoYg4Xov6Fw20gs5GQZFc1QjC7yNw=419E7875
      - JIRA_PROJECT_KEYS=API,FLXMES,FLEX,SRRHH
      - OUTPUT_DIR=../../Output
      - LOG_DIR=./logs
      - TEAMS_WEBHOOK_URL=https://default1f552e37d8254b9190aae742dcbc46.4d.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/e9ae762f7cf241b8940c74a493379ec9/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=QZJnuK9GO5Vwytx2P9a1wwL-WR1ZUpCfra0M1mlfMpY
      - NOTIFY_ON_ERROR=true
      - NOTIFY_ON_SUCCESS=true
      - TZ=America/Argentina/Buenos_Aires
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/bigquery-sa.json
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}  
networks:
  traefik:
    external:
      name: traefik-network
