version: '3.6'

services:
  flxwebapi:
    image: fabreguesm/flexxus-bi-etl:latest
    ports:
      - '5050:8080'
    networks:
      - traefik               
    deploy:      
      placement:
        constraints: ["${NODE}"] 
    environment:
      - LOAD_MODE=FULL
      - INCREMENTAL_DAYS=5
      - LOG_LEVEL=INFO
      - MYSQL_HELPDESK_HOST=mngservicios.flexxus.com.ar
      - MYSQL_HELPDESK_PORT=15172
      - MYSQL_HELPDESK_USER=root
      - MYSQL_HELPDESK_PASSWORD=Flexxus2023**
      - MYSQL_HELPDESK_DATABASE=helpdesk
      - MARIADB_ISABELLE_HOST=192.168.121.5
      - MARIADB_ISABELLE_PORT=3306
      - MARIADB_ISABELLE_USER=procesobi
      - MARIADB_ISABELLE_PASSWORD=12345678
      - MARIADB_ISABELLE_DATABASE=call_center
      - MARIADB_ASTERISK_HOST=192.168.121.5
      - MARIADB_ASTERISK_PORT=3306
      - MARIADB_ASTERISK_USER=procesobi
      - MARIADB_ASTERISK_PASSWORD=12345678
      - MARIADB_ASTERISK_DATABASE=asteriskcdrdb
      - FIREBIRD_SAR_HOST=192.168.121.178
      - FIREBIRD_SAR_DATABASE=//SAR/Base/DBADMINISTRADOR.GDB
      - FIREBIRD_SAR_USER=Sysdba    
      - FIREBIRD_SAR_PASSWORD=3122414422
      - FIREBIRD_SAR_PORT=3050
      - FIREBIRD_FLX_HOST=192.168.121.18
      - FIREBIRD_FLX_DATABASE=Z:\Datacenter\Bases\Demo Servicios\DB-DEMO SERVICIOS.gdb
      - FIREBIRD_FLX_PORT=3050
      - FIREBIRD_FLX_USER=Sysdba
      - FIREBIRD_FLX_PASSWORD=3122414422
      - BIGQUERY_PROJECT_ID=flexxus-bi
      - BIGQUERY_DATASET_SOPORTE=soporte
      - BIGQUERY_DATASET_JIRA=jira
      - BIGQUERY_ENABLED=true
      - JIRA_BASE_URL=https://flexxus.atlassian.net/
      - JIRA_EMAIL=martinf@flexxus.com.ar
      - JIRA_API_TOKEN=ATATT3xFfGF0N9_8eoB4C7zAUJ9KD6tUqe_skY-X9uin830Iw1dcKfYq9L1RGH6FpGWR5aPt8h8EgUd9b_9tACKVdOthYS8ShinLE-6bdSlRyqIp7oA07HaFw8kz455qV23plK8oxmFpmCcUC_ynj_vbrvZoYg4Xov6Fw20gs5GQZFc1QjC7yNw=419E7875
      - JIRA_PROJECT_KEYS=API,FLXMES,FLEX,SRRHH
      - OUTPUT_DIR=../../Output
      - LOG_DIR=./logs
      - SUITCRM_HOST=mngservicios.flexxus.com.ar
      - SUITCRM_PORT=15001
      - SUITCRM_USER=suitecrm
      - SUITCRM_PASSWORD=suitecrmFL#xxu5
      - SUITCRM_DATABASE=suitecrm
      - TEAMS_WEBHOOK_URL=https://default1f552e37d8254b9190aae742dcbc46.4d.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/e9ae762f7cf241b8940c74a493379ec9/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=QZJnuK9GO5Vwytx2P9a1wwL-WR1ZUpCfra0M1mlfMpY
      - NOTIFY_ON_ERROR=true
      - NOTIFY_ON_SUCCESS=true
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/bigquery-sa.json
      - GOOGLE_CREDENTIALS_BASE64=Wkl4aDVhcnlaKzdHcTg3THRGNkZYd2Z2cGxOUUFGWW5kQVR4VXRcbmoway93blJxczhKQUxWM3BoZi9sU3RzQ2pjSzAvSlFLNXBucmVDU2xta25tV1J4QXV3UWM4Zm9aRDJnLzVPSWpcbjdYL3Q1SXlIZUcvN09jTWZaWVpLL3Y1aU13S0JnUURhbHpKd2ZUYjFoMjdXczFHYnV0Ym9lMEdSOFVWSExUUmJcblRwQ05qdmtNNUFlL3V0RzBqRjJlaWVlOGpidEMwaWJ2QTBhUXR2N0g1TmJ5eFFCRzNld053Y2JVWUY3aWNrV1Zcbml2RFZsZTRUMGdJSEwwbVBpUXo2a01vVWxlYzk0MnFySkU4MnJORkU5Qi9adDBzUlpwckJXSDFhcjNTaC9jdVZcbjFETktad1NSWFFLQmdFREk3RVA5dU1iSTZ6QUtodkppUE4wa3hMVkd2UUFYUC9ET0xZaHFxWDFrY3dOT25IRk9cbm1NZm9iblRQQUJpZFlFWGRiT21oTWVjdHJQS1crUFRNeGNiZ1JxYnNRQS8wUWk2TVFhN3VmNXRRSXFmY2Y3bWtcbkJQL2NmYVJMREt3V2NERkdRWTlNWEJoR0tMV2JIOTQvOWMvcjZiZW5qUkFMTkd2dWplalV6bmFuQW9HQVRtR2hcbkNJMGR3L1VJWFp4M1N1dzRXNnkyMm1vMWVVeFFWZDFhSUNpQVRZc0c3RTFGSFFTb0hVMDk5M0tyRDA3ai94aWhcbm1RckZXVkJKYzB3SXlXQ1NZR3gzcTNmVERrZ0RnNWdLdTh2RFR3QWpFZ2gyekMxTXBoeDlHZHlXeXE1ZGRYalRcbm5ydGhYdVJhOTJxdVZGTUNjd29VQ1F5Wk9lMFRyMm9qNmkzK2lWRUNnWUE0T3VnOFdZWFlIOHdnT1ZDVmhPczVcbmEvYWtaTTg4cEtwYTZLWjgwWGV4aDdaV3RSNWdmeExwOGtKQ0NkWHdxMjZyYzZtMTEvcFF4ZUtGTmxQdW9xZkNcbk1WU0dMdTJhdkRmSmtZNXBWSzE3eVlyNnJFdmJMWEszRWtyaDdqRytvMnBWZDJGS0VxekxRSHdTVXlpS1R0bFlcblFaeGxOUDcyaTlNeG5iLzdjb0FIRkE9PVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImZsZXh4dXMtYmktc2VydmljZUBmbGV4eHVzLWJpLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwOTgyNzQyMzYzNjc0MTEzNzM1MCIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZmxleHh1cy1iaS1zZXJ2aWNlJTQwZmxleHh1cy1iaS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgInVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSIKfQo=
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}  
networks:
  traefik:
    external:
      name: traefik-network
